### ISSUE TITLE
KeyError: ''labels

### ISSUE THREAD

**Issue by MinaAku** [lobracost/MultimodalSDK_loader#2]
Thank you for your contribution to the project and the spirit of open source. Your achievements have brought great help to my work!

Unfortunately, when I follow the example to obtain the MOSI dataset and its characteristics, a KeyError appears. According to the error report, it is process_ There is a problem with the sequences method.

I can't solve this problem alone due to the code level and insufficient understanding of this project. I hope the author can help me, thank you!
The following are the specific error reports:

### 
Traceback (most recent call last):
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-928116c54826>", line 5, in <module>
    X_train, y_train, X_val, y_val, X_test, y_test = get_feature_matrix(dataset_name, seq_len)
  File "/Users/jawer/PycharmProjects/Txt-Ghp-AudUsedDetection/MOSIloader/MultimodalSDK_loader/process_dataset.py", line 158, in get_feature_matrix
  File "/Users/jawer/PycharmProjects/Txt-Ghp-AudUsedDetection/MOSIloader/MultimodalSDK_loader/process_dataset.py", line 152, in get_and_process_data
    log.success("Dataset processed")
  File "/Users/jawer/PycharmProjects/Txt-Ghp-AudUsedDetection/MOSIloader/MultimodalSDK_loader/process_dataset.py", line 114, in process_sequences
KeyError: 'labels'

**Comment by ItsDia** [comment]
i encountered same error, have you solved it?
